apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-frontend-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-frontend-app
  template:
    metadata:
      labels:
        app: java-frontend-app
    spec:
      containers:
        - name: java-frontend-app
          image: 218137097139.dkr.ecr.ap-south-1.amazonaws.com/java-app:BUILD_NUMBER_PLACEHOLDER
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
